language: java

# configure the Maven environment
before_install:
  - source <(curl -fsSL https://raw.github.com/daisy/maven-parents/travis/before_install)

# main task, run the verify goal
script: mvn verify

# if the build succeeds, deploy the artifact (tests are skipped)
after_success: 
  - source <(curl -fsSL https://raw.github.com/daisy/maven-parents/travis/after_success)

# whitelist; only deploy master branch
branches:
  only:
  - master

env:
  global:
  - secure: "AkkmnBVS9dxAYs/WhIqgRAX2uizmGL5eUkXPY9Fssnjz/w/jVCO9CAwagMmrYNzu22/qDBJlHOLLYCoG9J6KD16M/30l93PcV1g9HKQwA6FVB61rndXdVU9yYCFUasCjpRBPNw+pDg0G/bzdm0oURgYn2drFOTMrdyd1pwBneZQ="
  - secure: "BoH75jq1PscvuwiMFf/D97QlM52PFnRI7KQ4pSSHMzOIiJNwSIrqc8A4ofbu1v2xA+wNhK8VZVZflV94PD+oGIxvqxJH8Uwf2cocMwpR2W1pdca4bVBbI7aoOBXePo8krveb/MBYwoUGxhNFf7L5z2ERZ9MQ30MhTYcAXMAC0bU="
